import type { Context } from '@deepseek-ai/cordis';
import z from '@deepseek-ai/schemastery';
export { DynamicWorkflowService } from './service.js';
export * from './types.js';
export * from './capsule.js';
export * from './catalog.js';
export * from './runtime.js';
export * from './source-policy.js';
export * from './store.js';
export * from './builtins.js';
export * from './author.js';
export * from './scoped-review.js';
export * from './engine.js';
export declare const name = "dsh-external-workflow";
export declare const inject: string[];
export interface Config {
    readonly projectDirectory?: string;
    readonly personalDirectory?: string;
    readonly runDirectory?: string;
    readonly listToolName?: string;
    readonly runToolName?: string;
    readonly manageToolName?: string;
    readonly maxCapsuleBytes?: number;
    readonly maxCatalogEntries?: number;
    readonly maxAgents?: number;
    readonly maxConcurrency?: number;
    readonly maxResultChars?: number;
    readonly scriptSyncTimeoutMs?: number;
    readonly scriptWallTimeoutMs?: number;
    readonly defaultProvider?: string;
    readonly synthesisProvider?: string;
    readonly fastProvider?: string;
    readonly fastModelProvider?: string;
    readonly fastModel?: string;
    readonly fastMaxTokens?: number;
    readonly balancedProvider?: string;
    readonly balancedModelProvider?: string;
    readonly balancedModel?: string;
    readonly balancedMaxTokens?: number;
    readonly deepProvider?: string;
    readonly deepModelProvider?: string;
    readonly deepModel?: string;
    readonly deepMaxTokens?: number;
    readonly readOnlyDeniedTools?: string[];
    readonly readOnlyAllowedTools?: string[];
    readonly approvalMode?: 'never' | 'generated-and-local' | 'always';
    readonly availableTools?: string[];
    readonly availableMcp?: string[];
    readonly availableSkills?: string[];
    readonly maxRetainedRuns?: number;
}
export declare const Config: z<Config>;
export declare function apply(ctx: Context, config: Config): void;
declare const _default: {
    name: string;
    inject: string[];
    Config: z<Config>;
    apply: typeof apply;
};
export default _default;
